#!/bin/bash
#SBATCH --job-name=m50UCx
#SBATCH --output=m50n512.o
#SBATCH --error=m50n512.e
#SBATCH --mail-type=None
#SBATCH --mail-user=desika.narayanan@gmail.com
#SBATCH --time=96:00:00
#SBATCH --nodes=40
#SBATCH --ntasks-per-node=16
#SBATCH --ntasks-per-socket=8
#SBATCH --cpus-per-task=2
#SBATCH --distribution=cyclic:cyclic
#SBATCH --mem-per-cpu=3900mb
#SBATCH --partition=hpg2-compute
#SBATCH --account=narayanan
#SBATCH --qos=narayanan-b

module purge
module load intel/2018
module load grackle/3.1
module load gsl/2.4
module load openmpi/3.1.0
module load hdf5/1.10.1
module load fftw/2.1.5

export OMPI_MCA_pml="ucx"
export OMPI_MCA_btl="^vader,tcp,openib"
export OMPI_MCA_oob_tcp_listen_mode="listen_thread"

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
echo  "OMP_NUM_THREADS = $OMP_NUM_THREADS"

DATADIR=$SLURM_SUBMIT_DIR
cd $DATADIR/gizmo-mufasa
srun  --mpi=pmix $DATADIR/gizmo-mufasa/GIZMO $DATADIR/m50n512.param > $DATADIR/LOG

